---
title: "README"
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(knitr)
```

# covid19mx

Simple package to collect and preprocess information about covid in Mexico.

## From https://datos.cdmx.gob.mx/explore/?q=COVID

### Downloader included in the package

- Capacidad hospitalaria ZMVM
Esta base de datos  se realiza desde el Comando Metropolitano para la atención de la emergencia de COVID-19 en la Zona Metropolitana del Valle de México. El Comando está integrado por el Gobierno de México por medio de la Secretaría de Salud federal, el IMSS, el ISSSTE, el Gobierno de la Ciudad de México por medio de la Secretaría de Salud (SEDESA) y el Gobierno del Estado de México por medio d…
- Personas hospitalizadas por día por COVID-19
Esta base de datos contiene el total diario de personas hospitalizadas, confirmadas o sospechosas, por COVID-19 en los hospitales y centros médicos de la Zona Metropolitana del Valle de México (ZMVM). 
- Inventario de medidas por contingencia COVID-19
Esta base de datos muestra un listado de las medidas que ha puesto en marcha el Gobierno de la Ciudad de México y Alcaldías para atender la contingencia sanitaria de COVID-19.     
- Hospitales COVID-19
Este conjunto de datos incluye todos los hospitales de la CDMX y la Zona Metropolitana del Valle de México que tratan a pacientes con covid-19. 
- Covid-19 SINAVE Ciudad de México
Base del Sistema Nacional de Vigilancia Epidemiologica para el seguimiento a posibles casos de COVID-19 en la Ciudad de México.
- Casos a nivel nacional asociados a covid-19
Este conjunto de datos incluye todos los casos asociados a COVID-19 a nivel Ciudad de México, con contenido desagregado por sexo, edad, nacionalidad, padecimientos asociados, entre otros.
Downloaded via the API without the polygons

### Dowloaders to include

- Contratos adjudicados por COVID-19
En esta base de datos se encuentra la información de los contratos adjudicados por los diferentes entes del gobierno de la Ciudad de México para atender la emergencia sanitaria por COVID-19
- Inventario de Programas y Acciones Sociales ante el COVID-19
Esta base de datos incluye los programas y acciones sociales que se han puesto en marcha para atender los problemas de la población derivados de la pandemia de COVID-19.
- Afluencia preliminar en transporte público
Esta base de datos contiene los datos preliminares de la afluencia diaria de pasajeros en el transporte público en la Ciudad de México, reportados por los siguientes organismos: Sistema de Transporte Colectivo Metro (STC), Metrobus, Red de Transporte de Pasajeros (RTP), Sistema de Transporte Eléctrico Tren Ligero (STP-Tren Ligero), Sistema de Transporte Eléctrico Trolebus (STP-Trolebus) y Ecobici.
- Tamizajes CDMX
Esta base describe los registros del uso del servicio SMS-COVID. El servicio consiste en un tamizaje para la determinación de riesgo de infección por el virus SRAS-CoV-2, causante de la enfermedad por coronavirus COVID-19, con el objetivo de que los servicios de salud pública conozcan acerca de las personas que tienen mayor probabilidad de tener la enfermedad.El servicio consiste en un cuestion…
- Sitios de servicios de atención a la violencia de género durante contingencia COVID19
En esta base podrás encontrar los servicios de atención a la violencia hacia las mujeres y acceso a la justicia en la Ciudad de México proporcionados durante la contingencia sanitaria por covid-19 con la ubicación y los datos de contacto.
- Solicitudes y beneficiarios del Programa de Financiamiento para Microempresas
Esta base de datos muestra el total de solicitudes al programa de Financiamiento para Microempresas del Fondo para el Desarrollo Social de la Ciudad de México (FONDESO). 
- Solicitudes y derechohabientes al programa Seguro de Desempleo
Base de datos con las solicitudes al programa de Seguro de desempleo desagregado por ubicación del solicitante, dependientes económicos, discapacidad, grado de estudios, profesión, oficio, idioma, origen étnico y tiempo buscando empleo, entre otros.
- Establecimientos suspendidos por el Instituto de Verificación Administrativa ante la emergencia de COVID-19
Establecimientos con Suspensión de Actividades realizada por el Instituto de Verificación Administrativa ante la emergencia de COVID-19.
- Traslados a hospitales
Base de datos de los traslados a hospitales llevados a cabo en Ciudad de México, por probable caso positivo de COVID-19.La contabilización de los datos inicia con la remisión del usuario, cuyo origen se registra a través de una llamada al 911 o bien, atención por radio.
- Estaciones de transporte público temporalmente cerradas durante la fase 3 de COVID-19
Este conjunto de datos contiene las estaciones del Metro, el Metrobús y el Tren ligero que permanecerán temporalmente cerradas debido a su baja demanda de pasajeros para aumentar la frecuencia de paso en estaciones de mayor afluencia y así evitar aglomeraciones.
- Llamadas realizadas a Línea Mujeres
En esta base podrás encontrar toda la información de las llamadas realizadas al servicio Línea de Mujeres de LOCATEL desde noviembre de 2016. Esta información se actualizará semanalmente a partir del 6 de abril de 2020
- Hospitales y Centros de Salud
Ubicaciones georreferenciadas de los Hospitales y Centros de Salud del Gobierno de la Ciudad de México.

## Notes

 I'm a noob in R package writing any suggestions are welcomed.